### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by TiRajo** [T3rry7f/NoDRM#1]
Python wvclient.py "https://s3-bom-ww.cf.dash.row.aiv-cdn.net/dm/2$WdfaSOkHgWn5dTw0xCrp6uBUad0~/2966/bf9f/470f/4178-8afe5-3bc5cf2af5f6/55baa540-9cf0-4b98-a240-5e2929c9c166_corrected.mpd

Traceback (most recent call last):
  C:\NoDRM-1.0\NoDRM-1.0\WVClient\wvclient.py", line 126, in <module>
    cdm=WidevineCDM('http://widevine-proxy.appspot.com/proxy')      #
  File "C:\NoDRM-1.0\NoDRM-1.0\WVClient\wvclient.py", line 58, in __init__
    self.pub_key='30820122300d06092a864886f70d0101010500......03010001'.decode('hex')
AttributeError: 'str' object has no attribute 'decode'

**Comment by zackmark29** [comment]
You should edit the source code. If you are using python 3
should be bytes.fromhex(pubkey)

**Comment by TiRajo** [comment]
> You should edit the source code. If you are using python 3
> should be bytes.fromhex(pubkey)

Can you clearly explain which to be removed and addes or which version will works fine?

**Comment by zackmark29** [comment]
> > You should edit the source code. If you are using python 3
> > should be bytes.fromhex(pubkey)
> 
> Can you clearly explain which to be removed and added or which version will works fine?

upgrade some codes to python 3. Because it's original written in python 2
