### ISSUE TITLE
Netflix error

### ISSUE THREAD

**Issue by FugerZuer** [T3rry7f/NoDRM#10]
Even with the Netflix Server Certificate provided in the source code and compiled a new WidevineProxy.exe Netflix error: WidevineCoreLicenseError

**Comment by T3rry7f** [comment]
> Even with the Netflix Server Certificate provided in the source code and compiled a new WidevineProxy.exe Netflix error: WidevineCoreLicenseError

I havn't test on Netflix, if you can play any vidoe with widevinecdm.dll  by Chrome or other application , I think the repository will be work too. Maybe some cdm function call or args is not set  correct,that need to trace the cdm function .

**Comment by FugerZuer** [comment]
> > Even with the Netflix Server Certificate provided in the source code and compiled a new WidevineProxy.exe Netflix error: WidevineCoreLicenseError
> 
> I havn't test on Netflix, if you can play any vidoe with widevinecdm.dll by Chrome or other application , I think the repository will be work too. Maybe some cdm function call or args is not set correct,that need to trace the cdm function .

Yes it should work, but it doesn't I guess the second option is true. Some function is not called correctly. I can provide the server certificate and the python script if you would like for netflix to debug.

**Comment by Nintendocustom** [comment]
#3 and you will know what the issue is (I already fixed it).

**Comment by FugerZuer** [comment]
> #3 and you will know what the issue is (I already fixed it).

Can you provide the fix for it?
