### ISSUE TITLE
Getting "Truncated message."

### ISSUE THREAD

**Issue by VXsz** [T3rry7f/NoDRM#12]
Not sure if this is from me entering a wrong license URL, I first tried with Amazon Prime but it was a bit harder to understand (and know which request was the license's) so I tried something simpler: https://www.buydrm.com/multikey-demo

It's pretty simpler and clear what is what in the traffic tab, so I put the proxy server "https://wv-keyos.licensekeyserver.com" and entered the MPD (https://d2jl6e4h8300i8.cloudfront.net/netflix_meridian/4k-18.5!9/keyos-logo/g180-avc_a2.0-vbr-aac-128k/r30/dash-wv-pr/stream.mpd) which should work... but it spits this error every time, not sure what I'm doing wrong, and I would love if someone could tell me how to fix it/how it works

error traceback:

Traceback (most recent call last):
  File "wvclient.py", line 138, in <module>
    cdm.getContentKey(data)
  File "wvclient.py", line 104, in getContentKey
    responseMessage.ParseFromString(resp.content)
  File "...\pyenv-win\versions\2.7.18\lib\site-packages\google\protobuf\message.py", line 199, in ParseFromString
    return self.MergeFromString(serialized)
  File "...\.pyenv\pyenv-win\versions\2.7.18\lib\site-packages\google\protobuf\internal\python_message.py", line 1145, in MergeFromString
    raise message_mod.DecodeError('Truncated message.')
google.protobuf.message.DecodeError: Truncated message.

**Comment by T3rry7f** [comment]
> Not sure if this is from me entering a wrong license URL, I first tried with Amazon Prime but it was a bit harder to understand (and know which request was the license's) so I tried something simpler: https://www.buydrm.com/multikey-demo
> 
> It's pretty simpler and clear what is what in the traffic tab, so I put the proxy server "https://wv-keyos.licensekeyserver.com" and entered the MPD (https://d2jl6e4h8300i8.cloudfront.net/netflix_meridian/4k-18.5!9/keyos-logo/g180-avc_a2.0-vbr-aac-128k/r30/dash-wv-pr/stream.mpd) which should work... but it spits this error every time, not sure what I'm doing wrong, and I would love if someone could tell me how to fix it/how it works
> 
> error traceback:
> 
> Traceback (most recent call last):
> File "wvclient.py", line 138, in
> cdm.getContentKey(data)
> File "wvclient.py", line 104, in getContentKey
> responseMessage.ParseFromString(resp.content)
> File "...\pyenv-win\versions\2.7.18\lib\site-packages\google\protobuf\message.py", line 199, in ParseFromString
> return self.MergeFromString(serialized)
> File "....pyenv\pyenv-win\versions\2.7.18\lib\site-packages\google\protobuf\internal\python_message.py", line 1145, in MergeFromString
> raise message_mod.DecodeError('Truncated message.')
> google.protobuf.message.DecodeError: Truncated message.

It seems VMP required, this repository is not support now.

**Comment by VXsz** [comment]
> > Not sure if this is from me entering a wrong license URL, I first tried with Amazon Prime but it was a bit harder to understand (and know which request was the license's) so I tried something simpler: https://www.buydrm.com/multikey-demo
> > 
> > It's pretty simpler and clear what is what in the traffic tab, so I put the proxy server "https://wv-keyos.licensekeyserver.com" and entered the MPD (https://d2jl6e4h8300i8.cloudfront.net/netflix_meridian/4k-18.5!9/keyos-logo/g180-avc_a2.0-vbr-aac-128k/r30/dash-wv-pr/stream.mpd) which should work... but it spits this error every time, not sure what I'm doing wrong, and I would love if someone could tell me how to fix it/how it works
> > 
> > error traceback:
> > 
> > Traceback (most recent call last):
> > File "wvclient.py", line 138, in
> > cdm.getContentKey(data)
> > File "wvclient.py", line 104, in getContentKey
> > responseMessage.ParseFromString(resp.content)
> > File "...\pyenv-win\versions\2.7.18\lib\site-packages\google\protobuf\message.py", line 199, in ParseFromString
> > return self.MergeFromString(serialized)
> > File "....pyenv\pyenv-win\versions\2.7.18\lib\site-packages\google\protobuf\internal\python_message.py", line 1145, in MergeFromString
> > raise message_mod.DecodeError('Truncated message.')
> > google.protobuf.message.DecodeError: Truncated message.
> 
> It seems VMP required, this repository is not support now.

If I may ask, what is VMP?

Also do you know what's the license server for Amazon Prime? Thanks for your efforts :)

**Comment by T3rry7f** [comment]
> > > Not sure if this is from me entering a wrong license URL, I first tried with Amazon Prime but it was a bit harder to understand (and know which request was the license's) so I tried something simpler: https://www.buydrm.com/multikey-demo
> > > It's pretty simpler and clear what is what in the traffic tab, so I put the proxy server "https://wv-keyos.licensekeyserver.com" and entered the MPD (https://d2jl6e4h8300i8.cloudfront.net/netflix_meridian/4k-18.5!9/keyos-logo/g180-avc_a2.0-vbr-aac-128k/r30/dash-wv-pr/stream.mpd) which should work... but it spits this error every time, not sure what I'm doing wrong, and I would love if someone could tell me how to fix it/how it works
> > > error traceback:
> > > Traceback (most recent call last):
> > > File "wvclient.py", line 138, in
> > > cdm.getContentKey(data)
> > > File "wvclient.py", line 104, in getContentKey
> > > responseMessage.ParseFromString(resp.content)
> > > File "...\pyenv-win\versions\2.7.18\lib\site-packages\google\protobuf\message.py", line 199, in ParseFromString
> > > return self.MergeFromString(serialized)
> > > File "....pyenv\pyenv-win\versions\2.7.18\lib\site-packages\google\protobuf\internal\python_message.py", line 1145, in MergeFromString
> > > raise message_mod.DecodeError('Truncated message.')
> > > google.protobuf.message.DecodeError: Truncated message.
> > 
> > 
> > It seems VMP required, this repository is not support now.
> 
> If I may ask, what is VMP?
> 
> Also do you know what's the license server for Amazon Prime? Thanks for your efforts :)

VMP is supprted now, you can try WidevineWeb project.

**Comment by VXsz** [comment]
I will build it and test it shortly, can't wait to try it out

**Comment by VXsz** [comment]
It kinda does work, in the case of the demo example (https://www.buydrm.com/multikey-demo) only using init.mp4 works... but using an MPD won't and it will give an error

And I tried other services but it kept saying errors like `google.protobuf.message.DecodeError: Error parsing message` and other errors even after trying mp4 & mpd options

this is the mpd & license server im trying

mpd: `https://cdxaws-ak.akamaized.net/out/v1/87154852b91841699a9228201814f835/c96d37fedb44465f8a19c65563004303/2702b4dd304c43e88bcfa4f04f464736/manifest.mpd?aws.manifestfilter=video_height:144-1080`
license server: ` https://drm.cloud.insysvt.com/acquire-license/widevine?BrandGuid=2be49af0-6fbd-4511-8e11-3d6523185bb4&UserToken=<myToken, Will DM you if you need it>`

**Comment by T3rry7f** [comment]
> It kinda does work, in the case of the demo example (https://www.buydrm.com/multikey-demo) only using init.mp4 works... but using an MPD won't and it will give an error
> 
> And I tried other services but it kept saying errors like `google.protobuf.message.DecodeError: Error parsing message` and other errors even after trying mp4 & mpd options
> 
> this is the mpd & license server im trying
> 
> mpd: `https://cdxaws-ak.akamaized.net/out/v1/87154852b91841699a9228201814f835/c96d37fedb44465f8a19c65563004303/2702b4dd304c43e88bcfa4f04f464736/manifest.mpd?aws.manifestfilter=video_height:144-1080`
> license server: ` https://drm.cloud.insysvt.com/acquire-license/widevine?BrandGuid=2be49af0-6fbd-4511-8e11-3d6523185bb4&UserToken=<myToken, Will DM you if you need it>`

Ok ,fixed .you can try again.

**Comment by xhlove** [comment]
从mpd匹配pssh哪里建议再改一下

因为drm种类很多，mpd有时候会包含多种drm协议

https://dashif.org/identifiers/content_protection/

```python
matchObj = re.findall(r'ed.+\n.+(pssh.+)<', data.decode('utf-8'), re.M | re.I)
```

**Comment by T3rry7f** [comment]
> 从mpd匹配pssh哪里建议再改一下
> 
> 因为drm种类很多，mpd有时候会包含多种drm协议
> 
> https://dashif.org/identifiers/content_protection/
> 
> ```python
> matchObj = re.findall(r'ed.+\n.+(pssh.+)<', data.decode('utf-8'), re.M | re.I)
> ```

恩 代码写的很随意 没怎么测试  有问题的话可以帮提交requests

**Comment by VXsz** [comment]
> > It kinda does work, in the case of the demo example (https://www.buydrm.com/multikey-demo) only using init.mp4 works... but using an MPD won't and it will give an error
> > And I tried other services but it kept saying errors like `google.protobuf.message.DecodeError: Error parsing message` and other errors even after trying mp4 & mpd options
> > this is the mpd & license server im trying
> > mpd: `https://cdxaws-ak.akamaized.net/out/v1/87154852b91841699a9228201814f835/c96d37fedb44465f8a19c65563004303/2702b4dd304c43e88bcfa4f04f464736/manifest.mpd?aws.manifestfilter=video_height:144-1080`
> > license server: ` https://drm.cloud.insysvt.com/acquire-license/widevine?BrandGuid=2be49af0-6fbd-4511-8e11-3d6523185bb4&UserToken=<myToken, Will DM you if you need it>`
> 
> Ok ,fixed. you can try again.

Still the same issue using mpd and mp4: `google.protobuf.message.DecodeError: Error parsing message`

**Comment by T3rry7f** [comment]
> > > It kinda does work, in the case of the demo example (https://www.buydrm.com/multikey-demo) only using init.mp4 works... but using an MPD won't and it will give an error
> > > And I tried other services but it kept saying errors like `google.protobuf.message.DecodeError: Error parsing message` and other errors even after trying mp4 & mpd options
> > > this is the mpd & license server im trying
> > > mpd: `https://cdxaws-ak.akamaized.net/out/v1/87154852b91841699a9228201814f835/c96d37fedb44465f8a19c65563004303/2702b4dd304c43e88bcfa4f04f464736/manifest.mpd?aws.manifestfilter=video_height:144-1080`
> > > license server: ` https://drm.cloud.insysvt.com/acquire-license/widevine?BrandGuid=2be49af0-6fbd-4511-8e11-3d6523185bb4&UserToken=<myToken, Will DM you if you need it>`
> > 
> > 
> > Ok ,fixed. you can try again.
> 
> Still the same issue using mpd and mp4: `google.protobuf.message.DecodeError: Error parsing message`

Make sure PSSH data and the License response data is correct
