### ISSUE TITLE
mytvsuper站点请求响应400

### ISSUE THREAD

**Issue by 592767809** [T3rry7f/NoDRM#13]
我试用下面代码进行请求，但是得到400的响应码，响应内容为【Status 400: 80205 Invalid device ID】，请问是哪里出现了问题？

```python
import base64
import requests
from socket import *


def main():
    psshtext = 'AAAAR3Bzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAACcIARIQMxmyl/NdO54OgToR7nCr8hoDdHZiIgxORGMzT0RnM015d3c='

    sock = socket(AF_INET, SOCK_STREAM)
    sock.connect(('127.0.0.1', 8888))
    sock.send(base64.b64decode(psshtext.encode()))
    recvData = sock.recv(10240)
    sock.close()

    headers = {
        'User-Agent': 'Mozilla/5.0(WindowsNT10.0;Win64;x64)AppleWebKit/537.36(KHTML,likeGecko)Chrome/94.0.4596.0Safari/537.36Edg/94.0.978.0',
        'x-client-platform': 'html5',
        'x-service-id': 'super',
        'x-user-token': token,
    }

    response = requests.post('https://wv.drm.tvb.com/wvproxy/clicense?contentid=4778873', headers=headers, data=recvData)

    print(response.status_code)
    print(response.content)

if __name__ == '__main__':
    main()
```

**Comment by T3rry7f** [comment]
从返回报文来看貌似是接口问题, 如果服务器没有强制VMP的话, 这类问题只能自行检查了。

**Comment by 592767809** [comment]
> 从返回文看好像是接口问题，如果没有强制VMP的话，这些问题只能自己检查了。

我尝试抓包浏览器的请求体，然后放到python中进行重放测试，发现请求是正常的，可以排除ssl指纹检测等问题。然后我请求头中仅仅保留x-user-token，也是可以正常请求。但是当我使用WideVineProxy生成的请求体时，即使请求头一样，依然是获得400的响应码，那么是否可以说明这个网站是强制要求VMP？

**Comment by xhlove** [comment]
![image](https://user-images.githubusercontent.com/48152166/129064199-1906de30-6d9b-4d01-994c-2b32851be449.png)

这是浏览器的请求体和exe转换的license请求体差异

是否可以增加LicenseType类型的指定

另外RequestTime则修改为当前时间戳或指定

**Comment by T3rry7f** [comment]
> exe

这个问题之前有人提过，一般LicenseType设为Temporary即可，离线类型有些网站无法通过。RequestTime时间戳的问题倒是没太注意，好像影响不大，调用CDM时也没有这个参数的设置，调用的函数也没几个，也没必要搞成RPC方式了。主要这次没有私钥无法直接修改生成的请求信息。
