### ISSUE TITLE
Error "SyntaxError: invalid syntax"

### ISSUE THREAD

**Issue by heyasMM** [T3rry7f/NoDRM#15]
how to solve this errorr?

`C:\Users\heysmm\Downloads\Compressed\NoDRM-master\NoDRM-master\WVClient>python wvclient.py https://bitmovin-a.akamaihd.net/content/art-of-motion_drm/mpds/11331.mpd
  File "C:\Users\heysmm\Downloads\Compressed\NoDRM-master\NoDRM-master\WVClient\wvclient.py", line 127
    print "KID:",keyId,"KEY:",dkey.encode('hex')
          ^
SyntaxError: invalid syntax`

**Comment by 592767809** [comment]
盲猜你可能使用的py3环境，需要更改为py2

**Comment by T3rry7f** [comment]
update
