### ISSUE TITLE
大佬，请问WidevineWeb可以rpc通信吗？？

### ISSUE THREAD

**Issue by bluegatar** [T3rry7f/NoDRM#16]
就是用rpc的方式获得kid，key，而不用填web上的东西
因为要用到批量（或者WVClient能适配新版本也可以）
谢谢大佬掀牌子

**Comment by T3rry7f** [comment]
> 就是用rpc的方式获得kid，key，而不用填web上的东西
> 因为要用到批量（或者WVClient能适配新版本也可以）
> 谢谢大佬掀牌子

WidevineWeb也可以批量，可能速度会慢点，网站不强制VMP可以使用WVClient

**Comment by bluegatar** [comment]
大佬，我的意思是能够有直接调用的方式就好了，适合再编程已实现批量
现在这种web填写的不知道怎么能达到这个效果啊
恳请大佬出手填加这功能

**Comment by T3rry7f** [comment]
建议直接使用PywidevineX
