### ISSUE TITLE
Amazon error

### ISSUE THREAD

**Issue by FugerZuer** [T3rry7f/NoDRM#18]
Doesn't work with amazon, error:
`"downstreamReason":"vmp_validation_required","errorCode":"PRS.Dependency.DRM.Widevine.HdContentNotAllowed.VmpValidationRequired"`

**Comment by T3rry7f** [comment]
> Doesn't work with amazon, error:
> `"downstreamReason":"vmp_validation_required","errorCode":"PRS.Dependency.DRM.Widevine.HdContentNotAllowed.VmpValidationRequired"`

If you get this error by wvclient, you can try widevineweb

**Comment by FugerZuer** [comment]
> > Doesn't work with amazon, error:
> > `"downstreamReason":"vmp_validation_required","errorCode":"PRS.Dependency.DRM.Widevine.HdContentNotAllowed.VmpValidationRequired"`
> 
> If you get this error by wvclient, you can try widevineweb

I need it without web

**Comment by zackmark29** [comment]
> > > Doesn't work with amazon, error:
> > > `"downstreamReason":"vmp_validation_required","errorCode":"PRS.Dependency.DRM.Widevine.HdContentNotAllowed.VmpValidationRequired"`
> > 
> > 
> > If you get this error by wvclient, you can try widevineweb
> 
> I need it without web

Then write your own without web version. It's freely given and you're asking for impossible without the current solution for vmp
