### ISSUE TITLE
Keys using macOS

### ISSUE THREAD

**Issue by KiaN2020** [T3rry7f/NoDRM#19]
How can I use this on a Mac to get the keys?

**Comment by T3rry7f** [comment]
Reference test.py file

**Comment by KiaN2020** [comment]
I have 2 folders:

cdmapi_for_chromecdm_4.10.2209.0 (main folder)

inside the cdmapi_for_chromecdm_4.10.2209.0 main folder I have:

cdmapi.cpython-36m-x86_64-linux-gnu.so

cdmapi.cpython-37m-darwin.so



PywidevineX (main folder)

inside the PywidevineX main folder I have:

pywidevine (folder)

README.md

requirements.txt

test.py



(I have installed everything in the requirements document:

tqdm - Version installed 4.62.2
requests- Version installed 2.26.0
protobuf - Version installed 3.17.3
pycryptodome - Version installed 3.10.1
pycryptodomex - Version installed 3.10.1)


I still can't see how to use this in terminal

What am I missing?

Thank You.

**Comment by T3rry7f** [comment]
> cdmapi.cpython-37m-darwin.so

If you using macos you can try to rename `cdmapi.cpython-37m-darwin.so` to `cdmapi.so`

**Comment by KiaN2020** [comment]
Copied the `cdmapi.cpython-37m-darwin.so` into the pywidevine cdm folder and then renamed `cdmapi.cpython-37m-darwin.so` to `cdmapi.so` as you suggested and that worked.

Thank You.
