### ISSUE TITLE
widevineX problem

### ISSUE THREAD

**Issue by mohan585** [T3rry7f/NoDRM#20]
test.py is not executing it showing import error of cdmapi.
in that cdm.py there is no cdmapi from where is it imported. ? and 
Is this only for mac and linux ?
is this work for windows ?

**Comment by mohan585** [comment]
vpm is also not available ?

**Comment by T3rry7f** [comment]
Ubuntu or MacOS only ,cdmapi library no bet compiled  for windows,  vmp is available now.

**Comment by mohan585** [comment]
> Ubuntu or MacOS only ,cdmapi library not be compiled for windows, vmp is available now.

can you try cdmapi for windows 
https://source.chromium.org/chromium/chromium/src/+/master:media/cdm/api/
maybe this gonna help you for compling for windows.

**Comment by FloridaStream** [comment]
@T3rry7f 
can you implement a signature generation function in codelift so that you can sign license_request?

the goal is to do something similar to what you did in PywidevineX, but with windows support.

in this way it would be possible to generate the challenge with vmp, mark it, and decrypt it directly in the cdm.py code, dispensing with alternative codes.

would it be possible to publish the sourcecode from cdmapi? maybe it helps in implementing a windows version if you can't do it.
[device_client_id_blob device_vmp_blob.gz](https://github.com/T3rry7f/NoDRM/files/7041568/device_client_id_blob.device_vmp_blob.gz)

**Comment by T3rry7f** [comment]
Ok, cdmapi extension source code had uploaded, you can build the window version by yourself.

**Comment by mohan585** [comment]
> cdmapi extension source code had uploaded, you can build the windows version by yourself

Thanks bro. But While building that it was giving error :codelift.cpp(4): fatal error C1083: Cannot open include file: 'filters.h': No such file or directory

**Comment by T3rry7f** [comment]
> > cdmapi extension source code had uploaded, you can build the windows version by yourself
> 
> Thanks bro. But While building that it was giving error :codelift.cpp(4): fatal error C1083: Cannot open include file: 'filters.h': No such file or directory

[heade files](https://github.com/T3rry7f/NoDRM/tree/master/WideVineProxy/WideVineProxy/guesskey)

**Comment by mohan585** [comment]
> > > cdmapi extension source code had uploaded, you can build the windows version by yourself
> > 
> > 
> > Thanks bro. But While building that it was giving error :codelift.cpp(4): fatal error C1083: Cannot open include file: 'filters.h': No such file or directory
> 
> [header files](https://github.com/T3rry7f/NoDRM/tree/master/WideVineProxy/WideVineProxy/guesskey)

add all header files and builded but the error was :LINK : fatal error LNK1181: cannot open input file 'libcryptopp.a'
can you figure out this or solution.

**Comment by T3rry7f** [comment]
> > > > cdmapi extension source code had uploaded, you can build the windows version by yourself
> > > 
> > > 
> > > Thanks bro. But While building that it was giving error :codelift.cpp(4): fatal error C1083: Cannot open include file: 'filters.h': No such file or directory
> > 
> > 
> > [header files](https://github.com/T3rry7f/NoDRM/tree/master/WideVineProxy/WideVineProxy/guesskey)
> 
> add all header files and while building the error was :LINK : fatal error LNK1181: cannot open input file 'libcryptopp.a'
> can you figure out this or solution.

just complie the `libcryptopp.a`  static  library from [here](https://github.com/weidai11/cryptopp)

**Comment by xhlove** [comment]
直接编译cryptopp成库文件，然后setup.py里面直接引用可行吗

**Comment by T3rry7f** [comment]
> 直接编译cryptopp成库文件，然后setup.py里面直接引用可行吗

windows平时很少用也没装cygwin64就懒得编了，直接生成静态库引用应该就可以了

**Comment by mohan585** [comment]
I am getting this error after adding libcryptopp.a 

![pywv](https://user-images.githubusercontent.com/71021883/130735168-20a0eafb-f98a-46c4-bac0-a72b184554e3.JPG)
![pywv1](https://user-images.githubusercontent.com/71021883/130735191-90e7dcdf-f02a-408a-8319-276eb336ac43.JPG)

**Comment by mohan585** [comment]
Any solution for the above error

**Comment by T3rry7f** [comment]
> Any solution for the above error

[Updated](https://github.com/T3rry7f/NoDRM/releases/tag/1.1)

**Comment by xbstory** [comment]
[cdmapi.cp37-win_amd64.zip](https://github.com/T3rry7f/NoDRM/files/7046855/cdmapi.cp37-win_amd64.zip)

3.7.4下编译了一个

编译过程

- 配置vs环境
- 下载cryptopp850源代码，编译release版本生成lib，复制到cdmapi目录
- `setup.py`修改extra_objects = ['cryptlib.lib']
- 将cryptopp850的头文件、原guesser项目的wasm_src的头文件放到cdmapi下面一起，也可以直接全部将源代码复制过来，省事儿
- 执行编译命令`python setup.py build_ext --inplace`
- 在cdmapi目录下会生成pyd，注意不是build目录下

不过在3.8.5上编译暂时没有成功，如果后面成功会补充上来

![image](https://user-images.githubusercontent.com/48152166/130789633-e066afa1-4385-465c-975c-8f2243130a8e.png)

3.8.5下编译也成功了，vs编译cryptlib的时候选`/MD`

![LE4ZCFT1U@)0E92EF_O@06J](https://user-images.githubusercontent.com/48152166/130790495-73d31f10-182d-47fe-bd73-76929ef70df9.png)

[cdmapi.cp38-win_amd64.zip](https://github.com/T3rry7f/NoDRM/files/7046924/cdmapi.cp38-win_amd64.zip)

**Comment by mohan585** [comment]
what are the errors you faced on when compiling for 3.8.5. i am trying for 3.9.1 i got linking errors

**Comment by mohan585** [comment]
Compilation under 3.9.1 is also successful

**Comment by mohan585** [comment]
Compilation under 3.9.1 and 3.9.6 is also successful

3.9.1
[cdmapi.cp39-win_amd64.zip](https://github.com/T3rry7f/NoDRM/files/7047598/cdmapi.cp39-win_amd64.zip)

3.9.6
[cdmapi.cp3.9.6-win_amd64_.zip](https://github.com/T3rry7f/NoDRM/files/7047611/cdmapi.cp3.9.6-win_amd64_.zip)

**Comment by YFTX2015** [comment]
How to use cdmapi.cp39-win_amd64.pyd?

**Comment by MythodeaLoL** [comment]
> How to use cdmapi.cp39-win_amd64.pyd? @YFTX2015

compile or download the above files for your version of python

rename to `cdmapi.pyd`
then use the `import cdmapi`

in case of error check your installed python version.

**Comment by YFTX2015** [comment]
Is this usefull for tencent drm video?For example, '全职法师第5季超前点播'

**Comment by myrbrazz** [comment]
Please update the chrome_2209 CDM private key...

**Comment by NiKoCZ89** [comment]
this l1 cdm ain;t work lol

**Comment by 09kkthxbb** [comment]
Hi. How do I use the pywidevineX in Linux?

I've already installed python 3.9.6 and everything from the requirements.txt, and tqdm but I'm still getting this error

![Screenshot from 2021-08-28 10-18-42](https://user-images.githubusercontent.com/70685560/131203288-09c10c03-cd14-46f9-92ce-20b186f16ed3.png)

**Comment by mohan585** [comment]
Is vmp possible with pywidevinex ?

"downstreamReason":"vmp_validation_required","errorCode":"PRS.Dependency.DRM.Widevine.HdContentNotAllowed.VmpValidationRequired"

I am getting this error. Any solution

**Comment by zackmark29** [comment]
> Hi. How do I use the pywidevineX in Linux?
> 
> I've already installed python 3.9.6 and everything from the requirements.txt, and tqdm but I'm still getting this error
> 
> ![Screenshot from 2021-08-28 10-18-42](https://user-images.githubusercontent.com/70685560/131203288-09c10c03-cd14-46f9-92ce-20b186f16ed3.png)

You don't actually need tqdm. Just comment that line 4 from wvdecrypt.py

**Comment by jesshub** [comment]
For Mac - 3.9.7 compiled
[cdmapi.cpython-39-darwin.so.zip](https://github.com/T3rry7f/NoDRM/files/7156764/cdmapi.cpython-39-darwin.so.zip)
