### ISSUE TITLE
ValueError: RSA key format is not supported

### ISSUE THREAD

**Issue by hrz0x** [T3rry7f/NoDRM#23]
The example pssh and license url you provided works fine but when I try it with bitmovin or castlabs demo, it returns this error. 
Any ideas why?

```
/Users/X/NoDRM/PywidevineX/pywidevine/cdm/cdm.py:106: RuntimeWarning: Unexpected end-group tag: Not all data was converted
  message.ParseFromString(base64.b64decode(cert_b64))
Traceback (most recent call last):
  File "/Users/X/NoDRM/PywidevineX/test.py", line 41, in <module>
    challenge = wvdecrypt.get_challenge()
  File "/Users/X/NoDRM/PywidevineX/pywidevine/decrypt/wvdecrypt.py", line 46, in get_challenge
    return self.cdm.get_license_request(self.session)
  File "/Users/X/NoDRM/PywidevineX/pywidevine/cdm/cdm.py", line 214, in get_license_request
    service_public_key = RSA.importKey(session.service_certificate._DeviceCertificate.PublicKey)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Cryptodome/PublicKey/RSA.py", line 788, in import_key
    raise ValueError("RSA key format is not supported")
ValueError: RSA key format is not supported
```

I think it has to do with this line 
```
cert=requests.post(license_url,b'\x08\x04').content
```

Can you explain what that `b'\x08\x04'` is?

**Comment by T3rry7f** [comment]
> The example pssh and license url you provided works fine but when I try it with bitmovin or castlabs demo, it returns this error.
> Any ideas why?
> 
> ```
> /Users/X/NoDRM/PywidevineX/pywidevine/cdm/cdm.py:106: RuntimeWarning: Unexpected end-group tag: Not all data was converted
>   message.ParseFromString(base64.b64decode(cert_b64))
> Traceback (most recent call last):
>   File "/Users/X/NoDRM/PywidevineX/test.py", line 41, in <module>
>     challenge = wvdecrypt.get_challenge()
>   File "/Users/X/NoDRM/PywidevineX/pywidevine/decrypt/wvdecrypt.py", line 46, in get_challenge
>     return self.cdm.get_license_request(self.session)
>   File "/Users/X/NoDRM/PywidevineX/pywidevine/cdm/cdm.py", line 214, in get_license_request
>     service_public_key = RSA.importKey(session.service_certificate._DeviceCertificate.PublicKey)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Cryptodome/PublicKey/RSA.py", line 788, in import_key
>     raise ValueError("RSA key format is not supported")
> ValueError: RSA key format is not supported
> ```
> 
> I think it has to do with this line
> 
> ```
> cert=requests.post(license_url,b'\x08\x04').content
> ```
> 
> Can you explain what that `b'\x08\x04'` is?

Bitmovin wv license server has stopped working,  just try others.

**Comment by hrz0x** [comment]
> > The example pssh and license url you provided works fine but when I try it with bitmovin or castlabs demo, it returns this error.
> > Any ideas why?
> > ```
> > /Users/X/NoDRM/PywidevineX/pywidevine/cdm/cdm.py:106: RuntimeWarning: Unexpected end-group tag: Not all data was converted
> >   message.ParseFromString(base64.b64decode(cert_b64))
> > Traceback (most recent call last):
> >   File "/Users/X/NoDRM/PywidevineX/test.py", line 41, in <module>
> >     challenge = wvdecrypt.get_challenge()
> >   File "/Users/X/NoDRM/PywidevineX/pywidevine/decrypt/wvdecrypt.py", line 46, in get_challenge
> >     return self.cdm.get_license_request(self.session)
> >   File "/Users/X/NoDRM/PywidevineX/pywidevine/cdm/cdm.py", line 214, in get_license_request
> >     service_public_key = RSA.importKey(session.service_certificate._DeviceCertificate.PublicKey)
> >   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Cryptodome/PublicKey/RSA.py", line 788, in import_key
> >     raise ValueError("RSA key format is not supported")
> > ValueError: RSA key format is not supported
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I think it has to do with this line
> > ```
> > cert=requests.post(license_url,b'\x08\x04').content
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Can you explain what that `b'\x08\x04'` is?
> 
> Bitmovin wv license server has stopped working, just try others.

The original pywidevine with a L3 cdm is able to get keys from bitmovin and castlabs. 
```
headers = {
        "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
        "dt-custom-data": "eyJ1c2VySWQiOiJwdXJjaGFzZSIsInNlc3Npb25JZCI6ImRlZmF1bHQiLCJtZXJjaGFudCI6ImNsaWVudF9kZXYifQ==",
    }
pssh = 'AAAAMnBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAABISEG9rG5iE+D0Lhmob2KyjkNI='
license_url = "https://lic.staging.drmtoday.com/license-proxy-widevine/cenc/?assetId=agent-327"
```
I tried a different license server but It returns the same error.

**Comment by zackmark29** [comment]
> headers = {
>         "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
>         "dt-custom-data": "eyJ1c2VySWQiOiJwdXJjaGFzZSIsInNlc3Npb25JZCI6ImRlZmF1bHQiLCJtZXJjaGFudCI6ImNsaWVudF9kZXYifQ==",
>     }
> pssh = 'AAAAMnBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAABISEG9rG5iE+D0Lhmob2KyjkNI='
> license_url = "https://lic.staging.drmtoday.com/license-proxy-widevine/cenc/?assetId=agent-327"

```python
    pssh = 'AAAAMnBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAABISEG9rG5iE+D0Lhmob2KyjkNI='
    license_url = "https://lic.staging.drmtoday.com/license-proxy-widevine/cenc/?assetId=agent-327"
    #cert=requests.post(license_url,b'\x08\x04').content
    wvdecrypt = WvDecrypt(pssh)
    license=requests.post(
        url=license_url,
        data=wvdecrypt.get_challenge(),
        headers={
            "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
            "dt-custom-data": "eyJ1c2VySWQiOiJwdXJjaGFzZSIsInNlc3Npb25JZCI6ImRlZmF1bHQiLCJtZXJjaGFudCI6ImNsaWVudF9kZXYifQ==",
        }).json()
    
    license_b64 = license['license']
    wvdecrypt.update_license(license_b64)
    
    keys=wvdecrypt.start_process()

    for key in keys:
        logger.info(key)

```

```
[2021-08-26 14:58:16,206] INFO - pywidevine.cdm.cdm - opening new cdm session
[2021-08-26 14:58:16,207] INFO - pywidevine.cdm.cdm - session opened and init data parsed successfully
[2021-08-26 14:58:16,207] INFO - pywidevine.cdm.cdm - getting license request
[2021-08-26 14:58:16,330] INFO - pywidevine.cdm.cdm - license request created
[2021-08-26 14:58:18,075] INFO - pywidevine.cdm.cdm - decrypting provided license
[2021-08-26 14:58:18,190] INFO - pywidevine.cdm.cdm - All keys has been decrypted
[2021-08-26 14:58:18,191] INFO - __name__ - 6f6b1b9884f83d0b866a1bd8aca390d2:259a3693dcc18c3a5974719b436a897e
[2021-08-26 14:58:18,191] INFO - __name__ - 3081242082b936aea58d1595ef3bc407:1c2f938b50d902bb2ac0319fb0b30905
[2021-08-26 14:58:18,191] INFO - __name__ - d6e4d9a41c2b3bf8b9d6e510ecfa65e5:e7ea962fbdd0aa6b0aaaa0c9ac56efff
[2021-08-26 14:58:18,191] INFO - __name__ - c72b61de92d93ea3ade92cca1fb31f1f:508a04e69a8db0de85676b432d91faa5
[2021-08-26 14:58:18,192] INFO - __name__ - 56cbb1d6682c36ad81680d089d6da1eb:eb55443310f2d4985c8a4a3f7dbd9485
```

**Comment by VCDEV1** [comment]
@zackmark29 Can you please say how you edited the PywidevineX to get the keys in kid:key format like in the example above! Currently it is giving key in wierd format!

**Comment by zackmark29** [comment]
> @zackmark29 Can you please say how you edited the PywidevineX to get the keys in kid:key format like in the example above! Currently it is giving key in wierd format!

Edit def start_process from here:
"C:\test\pywidevineX\pywidevine\decrypt\wvdecrypt.py"

```python
def start_process(self):
    return [f'{k.kid.hex()}:{k.key.hex()}' for k in self.cdm.get_keys(self.session) if k.type == 'CONTENT']
```

**Comment by VCDEV1** [comment]
> > @zackmark29 Can you please say how you edited the PywidevineX to get the keys in kid:key format like in the example above! Currently it is giving key in wierd format!
> 
> Edit def start_process from here:
> "C:\test\pywidevineX\pywidevine\decrypt\wvdecrypt.py"
> 
> ```python
> def start_process(self):
>     return [f'{k.kid.hex()}:{k.key.hex()}' for k in self.cdm.get_keys(self.session) if k.type == 'CONTENT']
> ```

@zackmark29 Thank you so much! it works just as I wanted!

**Comment by mohan585** [comment]
> > @zackmark29 Can you please say how you edited the PywidevineX to get the keys in kid:key format like in the example above! Currently it is giving key in wierd format!
> 
> Edit def start_process from here:
> "C:\test\pywidevineX\pywidevine\decrypt\wvdecrypt.py"
> 
> ```python
> def start_process(self):
>     return [f'{k.kid.hex()}:{k.key.hex()}' for k in self.cdm.get_keys(self.session) if k.type == 'CONTENT']
> ```

Is Vmp is supported ? i am getting error about vmp_validation_required

**Comment by zackmark29** [comment]
> > > @zackmark29 Can you please say how you edited the PywidevineX to get the keys in kid:key format like in the example above! Currently it is giving key in wierd format!
> > 
> > 
> > Edit def start_process from here:
> > "C:\test\pywidevineX\pywidevine\decrypt\wvdecrypt.py"
> > ```python
> > def start_process(self):
> >     return [f'{k.kid.hex()}:{k.key.hex()}' for k in self.cdm.get_keys(self.session) if k.type == 'CONTENT']
> > ```
> 
> Is Vmp is supported ? i am getting error about vmp_validation_required

Yes vmp is supported.
Try to post your issue and the error so @T3rry7f can fix it
