### ISSUE TITLE
LicenseSever Protected

### ISSUE THREAD

**Issue by Severus5401** [T3rry7f/NoDRM#24]
Hi,

Im playing with a provider that use an intermediate WebService so player -> request to WS -> WS to License Server.
That is posible, maybe im not looking for the good request in network logs, can i retrieve license url with EME Logger extension?

It will posible to decrypt keys passing only the answer from network logs and the ssl certificate?

Thanks

**Comment by T3rry7f** [comment]
It obviously could not , you can get decrypt keys with guesser extension.

**Comment by Severus5401** [comment]
Yes, i can but the provider use 4 keys for each manifest and one of them is not used in webbrowser (1080p) for that im looking your project.

**Comment by T3rry7f** [comment]
If 1080p is supported in widevine level 3 you can have a try, but you need to get the pssh and license url firstly .

**Comment by Severus5401** [comment]
yes its supported, pssh is not a problem, the problem is with license url because they have an WS intermediary ...

**Comment by T3rry7f** [comment]
> intermediary

You can get license data from WS server,,but maybe you need to analyse the website js/wasm code.

**Comment by Severus5401** [comment]
And if 1080p is only supported with L1 any solution?

**Comment by T3rry7f** [comment]
L1 private key required
