### ISSUE TITLE
challenge is not generated properly 

### ISSUE THREAD

**Issue by Nintendocustom** [T3rry7f/NoDRM#3]
I played around with the tool a bit and noticed that sometimes I get an error message when I request the license. After noticing this, I took a closer look at the tool and found out that the challenge is not generated correctly. For example, the LicenseType is set to offline (default is the best). And the request time is always 0.

**Comment by T3rry7f** [comment]
I try to generate License type from   Persistent  to Temporary , maybe cause of this.
