### ISSUE TITLE
Mismatched decryption key (trying to use different license server)

### ISSUE THREAD

**Issue by ParkRoger** [T3rry7f/NoDRM#7]
I modified the code to python3. The test DRM video works great. But While trying other DRM servers that do not just take the license request data unlike the `appspot.com/proxy` does.
SO instead of first getting the post request working I tried to directed test the license from the repose in network tab 
```python
base64.b64decode("CAIS8QMKNAoQ06iVTjUZvOSV8aP36B2xCBIQ06iVTjUZvOSV8aP36B2xCBoAIAEoADgAQABI4rmgiAYSFAgBEAEYACAAKAAwADgAQgBIAFAKGmYSEJk8rZm/zpSPKx2AQTL13dwaUEiVluvtLe/wTD2mKWzZsloM2LeHDl0jYJ080lkxv6HZV7cm8pQJ9nlCZqzS6QyqCTHS+gDlD2kTwPkoc1kOUcV+UuomUC1JNZ795xWYZNA+IAEaYgoQoa0MW2ibX7ea6+5QV/ZtVxIQFm79RRsedJKpRbJj4yN8BRogd24C+AHrlSvvtLi64tN4FlulzIVmSzphh6njLibXAsIgAigBQhIKEGtjMTYAAAAARsSk64AAAAhiAkhEGmIKELcSKbnJAl/rlt7aMdpq88wSEHKAH1hlNOjF4P572zDaCsQaIPHtt3IZGrHDNV7aIxlkrsUQ+OAePkzVZmdwBB5/EcXTIAIoAUISChBrYzE2AAAAAEbEpOuAAAAIYgJTRBplChAWnZYvV/pQpqjFlKE9aVIuEhDeLxzz6POywUMzBybo5a0dGiDtN0b4n99fzWccETiXdJwtj8GmUXmpTcRoi0zWbB7qLyACKAFCEgoQa2MxNgAAAABGxKTrgAAACGIFQVVESU8g4rmgiAY449yVmwZQBRogglrXPfnMILkVrCcraB8gMSiQKpDAgU60YmeMLTGrPBcigAJOP4o3OFnvRp+rc2qpMD8Dlg/8LP0qmRWSB/iKO0OYX4dMXCZUwGkI5Z46/03jt19mSh7hZ7D4O/bbWFEQ/Ns2kL14fX1wo8+qG6EP/LTTJ3pjS5/y21gnlBfei/48Rnn42y5Wokc1U9Yy17315SNCWNVreRDay1FZ4ouLbT91/3s/OwgF/UIe6qjVjVLvdO8KXfVJxzElNzcGAiEgBy5QR4YHSbSuXnYcM4VpxXTKOL28juNoetXOPikmXQZuzQIAsgCx9n5zz9XMFH5qAk2eXMEhy72b38SUwZrvccfsFsNV+PyQhnmAxH03PxkF4hWmymkElI1aSRSM9nJ5C4GvOjMKMTE2LjQuNSBCdWlsdCBvbiBKdW4gMjQgMjAyMSAyMTozOTowOCAoMTYyNDU5NTkxMilAAUqAAgAAAAIAAAEAAAUAEEbEpOtCfP1xAAAAUAAAABAAAABiAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAuAAAABAAAADKAAAAEAAAANwAAAAQAAAAAAAAAAAAAAEEAAAAEAAAARwAAAAQAAABLgAAABAAAAFAAAAAEAAAAAAAAAAAAAABBAAAABAAAAGAAAAAEAAAAZIAAAAQAAABpAAAABAAAAAAAAAAAAAAAQQAAAAQhaIpIXlor/4ALUxh1IeipXmwCQZjezpa4IVVShtG8t5YAA==")
```

and then send that to 
```python
responseMessage.ParseFromString(data_rep)
```

But I get a different keys compared to `widevine-l3-guesser` gives me.
```
wvclient.py
--key a1ad0c5b689b5fb79aebee5057f66d57:a420743fa3ca181d2c1961ea7b719b80
--key b71229b9c9025feb96deda31da6af3cc:2301c0081b29cef50d29a2aa62e19e6c
--key 169d962f57fa50a6a8c594a13d69522e:96a37673bc70b6e56978dd5eca35e4ba
```
vs 
```
widevine.l3.guesser
WidevineDecryptor: Found key: 3b8591cc5a3e822ef4eb10bc2aaf7efb (KID=a1ad0c5b689b5fb79aebee5057f66d57)
content_key_decryption.js:66 WidevineDecryptor: Found key: c63c0927f19833f328a76119f8576d5c (KID=b71229b9c9025feb96deda31da6af3cc)
content_key_decryption.js:66 WidevineDecryptor: Found key: a29705bb47a65c642d2644c68d53b945 (KID=169d962f57fa50a6a8c594a13d69522e)
```

**Comment by T3rry7f** [comment]
> I modified the code to python3. The test DRM video works great. But While trying other DRM servers that do not just take the license request data unlike the `appspot.com/proxy` does.
> SO instead of first getting the post request working I tried to directed test the license from the repose in network tab
> 
> ```python
> base64.b64decode("CAIS8QMKNAoQ06iVTjUZvOSV8aP36B2xCBIQ06iVTjUZvOSV8aP36B2xCBoAIAEoADgAQABI4rmgiAYSFAgBEAEYACAAKAAwADgAQgBIAFAKGmYSEJk8rZm/zpSPKx2AQTL13dwaUEiVluvtLe/wTD2mKWzZsloM2LeHDl0jYJ080lkxv6HZV7cm8pQJ9nlCZqzS6QyqCTHS+gDlD2kTwPkoc1kOUcV+UuomUC1JNZ795xWYZNA+IAEaYgoQoa0MW2ibX7ea6+5QV/ZtVxIQFm79RRsedJKpRbJj4yN8BRogd24C+AHrlSvvtLi64tN4FlulzIVmSzphh6njLibXAsIgAigBQhIKEGtjMTYAAAAARsSk64AAAAhiAkhEGmIKELcSKbnJAl/rlt7aMdpq88wSEHKAH1hlNOjF4P572zDaCsQaIPHtt3IZGrHDNV7aIxlkrsUQ+OAePkzVZmdwBB5/EcXTIAIoAUISChBrYzE2AAAAAEbEpOuAAAAIYgJTRBplChAWnZYvV/pQpqjFlKE9aVIuEhDeLxzz6POywUMzBybo5a0dGiDtN0b4n99fzWccETiXdJwtj8GmUXmpTcRoi0zWbB7qLyACKAFCEgoQa2MxNgAAAABGxKTrgAAACGIFQVVESU8g4rmgiAY449yVmwZQBRogglrXPfnMILkVrCcraB8gMSiQKpDAgU60YmeMLTGrPBcigAJOP4o3OFnvRp+rc2qpMD8Dlg/8LP0qmRWSB/iKO0OYX4dMXCZUwGkI5Z46/03jt19mSh7hZ7D4O/bbWFEQ/Ns2kL14fX1wo8+qG6EP/LTTJ3pjS5/y21gnlBfei/48Rnn42y5Wokc1U9Yy17315SNCWNVreRDay1FZ4ouLbT91/3s/OwgF/UIe6qjVjVLvdO8KXfVJxzElNzcGAiEgBy5QR4YHSbSuXnYcM4VpxXTKOL28juNoetXOPikmXQZuzQIAsgCx9n5zz9XMFH5qAk2eXMEhy72b38SUwZrvccfsFsNV+PyQhnmAxH03PxkF4hWmymkElI1aSRSM9nJ5C4GvOjMKMTE2LjQuNSBCdWlsdCBvbiBKdW4gMjQgMjAyMSAyMTozOTowOCAoMTYyNDU5NTkxMilAAUqAAgAAAAIAAAEAAAUAEEbEpOtCfP1xAAAAUAAAABAAAABiAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAuAAAABAAAADKAAAAEAAAANwAAAAQAAAAAAAAAAAAAAEEAAAAEAAAARwAAAAQAAABLgAAABAAAAFAAAAAEAAAAAAAAAAAAAABBAAAABAAAAGAAAAAEAAAAZIAAAAQAAABpAAAABAAAAAAAAAAAAAAAQQAAAAQhaIpIXlor/4ALUxh1IeipXmwCQZjezpa4IVVShtG8t5YAA==")
> ```
> 
> and then send that to
> 
> ```python
> responseMessage.ParseFromString(data_rep)
> ```
> 
> But I get a different keys compared to `widevine-l3-guesser` gives me.
> 
> ```
> wvclient.py
> --key a1ad0c5b689b5fb79aebee5057f66d57:a420743fa3ca181d2c1961ea7b719b80
> --key b71229b9c9025feb96deda31da6af3cc:2301c0081b29cef50d29a2aa62e19e6c
> --key 169d962f57fa50a6a8c594a13d69522e:96a37673bc70b6e56978dd5eca35e4ba
> ```
> 
> vs
> 
> ```
> widevine.l3.guesser
> WidevineDecryptor: Found key: 3b8591cc5a3e822ef4eb10bc2aaf7efb (KID=a1ad0c5b689b5fb79aebee5057f66d57)
> content_key_decryption.js:66 WidevineDecryptor: Found key: c63c0927f19833f328a76119f8576d5c (KID=b71229b9c9025feb96deda31da6af3cc)
> content_key_decryption.js:66 WidevineDecryptor: Found key: a29705bb47a65c642d2644c68d53b945 (KID=169d962f57fa50a6a8c594a13d69522e)
> ```

Make sure the lic_request_data is macthed lic_response_data .

**Comment by ParkRoger** [comment]
Actually I took a deeper look l3-guesser https://github.com/Satsuoni/widevine-l3-guesser/issues/8 looks like it has the same issue too somehow. I'm guessing the site is doing something funky. Since on each run with same data passed to `responseMessage.ParseFromString(data_rep)` I still get different keys.

**Comment by zackmark29** [comment]
Like I said, give me the license url and pssh. I'll test in my tool

**Comment by ParkRoger** [comment]
More debugging later I see the only data that's different on each run is `recvData = self.sock.recv(10240)` received from the proxy.
I'm not sure if its supposed to be that way I'm relatively new to DRM so having a Hard time debugging everything.

**Comment by ParkRoger** [comment]
@T3rry7f  I'm not sure if you're using the l3-guesser code in anyway but some aspects of it were fixed just now maybe the same thing leads to a different key here? 
https://github.com/Satsuoni/widevine-l3-guesser/commits/background
