### ISSUE TITLE
onreject promise error

### ISSUE THREAD

**Issue by chef112** [T3rry7f/NoDRM#8]
anyone help with this .. any time i pass mpd i get onreject promise error ?

**Comment by T3rry7f** [comment]
check if widevine pssh data is correct

**Comment by alienmaster9** [comment]
what provider you have issue contact me at telegram may be i could help @alienmaster9  @chef112

**Comment by chef112** [comment]
Hey @alienmaster9  thanks for the reply  I managed to get it going 
I've got my own cdm just now and it works with most providers I made php header request and post data files 

If you don't mind I'll add you on telegram as I got a few other questions you may be able to help with? 

Thanks for the reply

**Comment by alienmaster9** [comment]
Am working with this stuff so long long time I could help with it.
