### ISSUE TITLE
peacocktv

### ISSUE THREAD

**Issue by moonmuaaz000** [T3rry7f/NoDRM#9]
Is it possible to make it work with peacocktv.com?
Because I didn't get any response. Even with pssh headers and license url.

**Comment by chef112** [comment]
does your headers and url work with other cdm ?

**Comment by moonmuaaz000** [comment]
No it doesn't.
Registration is free. Please give it a try.

**Comment by alienmaster9** [comment]
i would suggest make a php script with headers required for making a license request and then use it here it works.

**Comment by chef112** [comment]
What @alienmaster9 said is correct 
I've tried this with other providers that required extra information in the headers or some sort of post challenge 

Some are more complicated than others lol 
So far I got a few of the bigger providers to work

**Comment by moonmuaaz000** [comment]
> i would suggest make a php script with headers required for making a license request and then use it here it works.

I don't think it will work because signature headers have hmac (which most providers don't have it) which is required to do hash for license 
This is the reason why pywidevine and wvclient doesn't work

**Comment by T3rry7f** [comment]
> > i would suggest make a php script with headers required for making a license request and then use it here it works.
> 
> I don't think it will work because signature headers have hmac (which most providers don't have it) which is required to do hash for license request.
> 
> This is the reason why pywidevine and wvclient and PHP scripts doesn't work on this perticular site


> > i would suggest make a php script with headers required for making a license request and then use it here it works.
> 
> I don't think it will work because signature headers have hmac (which most providers don't have it) which is required to do hash for license request.
> 
> This is the reason why pywidevine and wvclient and PHP scripts doesn't work on this perticular site

> Hi,@moonmuaaz000. I don't have a try, but i think it will be easy by yourself if you know how to capture http request and master skills of Javascript.

**Comment by xhlove** [comment]
peacocktv用不了是因为最终发送的license数据修改过了，得分析js怎么修改的才行的（左边是没有修改之前，protocol数据，右边是最终发送的数据）

![image](https://user-images.githubusercontent.com/48152166/128341417-db178d4f-5a57-41d8-9178-39c344cd9499.png)

**Comment by T3rry7f** [comment]
> peacocktv用不了是因为最终发送的license数据修改过了，得分析js怎么修改的才行的（左边是没有修改之前，protocol数据，右边是最终发送的数据）
> 
> ![image](https://user-images.githubusercontent.com/48152166/128341417-db178d4f-5a57-41d8-9178-39c344cd9499.png)

乱七八糟的网站太多了，都懒得去看。有些实在懒得分析的话，直接nodejs去调用就完事了。

**Comment by xhlove** [comment]
是的，这种没必要管

**Comment by alienmaster9** [comment]
I have signature calculation for peacock but am not wishing to share

**Comment by moonmuaaz000** [comment]
> I have signature calculation for peacock but am not wishing to share

Please try to fish somewhere else I never asked you to share.
Thank you

**Comment by moonmuaaz000** [comment]
> > Hi,@moonmuaaz000. I don't have a try, but i think it will be easy by yourself if you know how to capture http request and master skills of Javascript.

Hi t3rry thank you for noticing but is there any way I can get response from this license url with the android challenge?

From what I can gather:
The website peacock uses the actual payload (the body data)
This gets pushed in the HMAC function with a key often 128 bit
Which hashes the payload. Then the server hashes the payload with the same 128 bit key and compare both signatures (signatures based on license body in the headers of license url ) the signature has nothing to do with the protobuf directly is just hashes the body with HMAC. you can probably extract the HMAC key from Android with Frida or something, but I have not managed to do obtain hmac key which is different for different services. Is it possible to obtain hmac key from the chrome cdm or with this. Extension is working because it is getting actual body of chrome CDM from eme interception . Is it possible to intercept eme for Android?

I would really appreciate if you can look more into this.
Thanks

**Comment by 592767809** [comment]
当我直接抓包浏览器的请求体时，是可以正常返回内容的，如下图
![1](https://user-images.githubusercontent.com/42226845/129067491-046ed29c-a58b-4d7c-b496-e3954fbdb631.jpg)
但是当我使用exe来生成请求体的时候，就遇到了问题，返回的响应码为422，如下图
![2](https://user-images.githubusercontent.com/42226845/129067560-c54e9468-8a2d-4663-bf14-e0b00361bc8a.jpg)
这使得无法直接在python中获取密钥

**Comment by 592767809** [comment]
![1](https://user-images.githubusercontent.com/42226845/129486560-484c983e-80c9-4894-8be5-cd3b7431c022.jpg)
使用调用浏览器的方式可以正确获取到200的响应

**Comment by T3rry7f** [comment]
> ![1](https://user-images.githubusercontent.com/42226845/129486560-484c983e-80c9-4894-8be5-cd3b7431c022.jpg)
> 使用调用浏览器的方式可以正确获取到200的响应

是的 浏览器默认开启VMP 生成的请求数据没特殊限制的话基本不会有问题

**Comment by ischmidt20** [comment]
Hi,

So what is the solution here? I am not too familiar with pywidevine, but I was able to get it working with other platforms (beIN). What exactly do I need to take from devtools to be able to obtain the keys successfully? I am sorry for not understanding based on what is already here
